# Generated by Django 4.1.7 on 2023-06-01 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produits', '0002_categories_alter_matelas_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='dimensions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='matelas',
            name='dimension',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.dimensions'),
        ),
        migrations.AlterField(
            model_name='matelas',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produits.types'),
        ),
    ]
